# Generated by Django 3.2.5 on 2021-07-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('traveller', models.CharField(max_length=254)),
                ('email_id', models.EmailField(max_length=254)),
                ('destination', models.IntegerField(null=True)),
                ('total_travellers', models.IntegerField(null=True)),
                ('budget_per_person', models.IntegerField(null=True)),
                ('last_update_time', models.IntegerField(null=True)),
                ('creation_time', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_booking_details',
            },
        ),
    ]
