# Generated by Django 3.2.5 on 2021-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('traveller', models.CharField(max_length=254)),
                ('email_id', models.EmailField(max_length=254)),
                ('destination', models.IntegerField()),
                ('total_travellers', models.IntegerField()),
                ('budget_per_person', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_booking_details',
            },
        ),
    ]
