# Generated by Django 3.2.5 on 2021-07-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='creation_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='last_update_time',
            field=models.IntegerField(null=True),
        ),
    ]
