# Generated by Django 3.2.5 on 2021-07-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20210724_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='budget_per_person',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='destination',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='total_travellers',
            field=models.IntegerField(null=True),
        ),
    ]
